#ifndef SSP_CONTROLLER_PRINTDEFINITIONS_H
#define SSP_CONTROLLER_PRINTDEFINITIONS_H

#define INIT 1
#define CTRL 2
#define PRSC 4
#define CTRL_PATH 8
// #define PRINT (INIT | CTRL | PRSC | CTRL_PATH)
#define PRINT 0

#endif //SSP_CONTROLLER_PRINTDEFINITIONS_H
